menu:
- {name: 'publications', url: '/publications'}
- {name: 'courses', url: '/courses'}
- {name: 'cv', url: '/cv'}
- {name: 'contact', url: '/contact'}
- {name: 'science', url: '/science/science.html'}
- {name: 'misc', url: '/misc/misc.html'}

courses:
- {name: 'Coming Soon', url: 'coming-soon'}

science:
- {name: 'Small Projects', url: '/science'}

misc:
- {name: 'Misc.', url: '/misc'}


social:
- {icon: 'github', link: 'https://github.com/syueqiao'}
- {icon: 'linkedin', link: 'https://www.linkedin.com/in/jessica-s-888427191/'}

contacts:
- {name: 'Jessica Shen', title: 'PhD Student', department: 'Molecular Genetics', institution: 'University of Toronto', email: 'jessicayq.shen[at]mail.utoronto.ca', office: 'Under a mossy rock', image: 'assets/img/contact.jpg'}

# Customize site text
pagination:
  next_page: 'Newer'
  previous_page: 'Older'